### ISSUE TITLE
Peer-to-Peer Code review: @Teshome-@Amina-@Selase

### ISSUE THREAD

**Issue by dewslyse** [Tadesse-Alemayehu/Awesome-books#4]
- Well-structured and easy to read code 💯 
- Nice use of function to switch to active section 💪🏽 

[Optional] Consider removing the min length on inputs. What if an author's name is a single alphabet 😉

**Comment by TadesseDev** [comment]
## Dars, @Amina @dewslyse @TesheMaximillan
- We have fixed the issue in https://github.com/Tadesse-Alemayehu/Awesome-books/pull/5/commits/c755badd6e0eedd4912bddd83dfd173dd6ab9b5b commit hash. ✔
- Fill free to re-do the issue check. 😎
- Check out the [live page](https://tadesse-alemayehu.github.io/Awesome-books/#new-book-section) also. 💡
- We thank you ✌
